/**
 * Golden parity tests: feed real CNKI inputs into our converter and verify the
 * output is byte-exact equal to the Python backend's output.
 *
 * The fixtures are generated by ../../scripts/generate-fixtures.mjs and
 * regenerated periodically against the reference Python implementation.
 */
import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cnkiToBib } from './index';

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), '__fixtures__');

interface Fixture {
  name: string;
  input: string;
  expected: string;
}

function loadFixtures(): Fixture[] {
  const files = readdirSync(FIXTURES_DIR);
  const inputs = files.filter((f) => f.endsWith('.cnki.txt'));
  return inputs.map((f) => {
    const name = f.replace(/\.cnki\.txt$/, '');
    return {
      name,
      input: readFileSync(join(FIXTURES_DIR, f), 'utf8'),
      expected: readFileSync(join(FIXTURES_DIR, `${name}.bib`), 'utf8'),
    };
  });
}

describe('cnki2bib golden parity', () => {
  const fixtures = loadFixtures();

  it.each(fixtures)('produces Python-equivalent output for $name', ({ input, expected }) => {
    const actual = cnkiToBib(input);
    expect(actual).toBe(expected);
  });
});
